import { PurchaseOrder } from './PurchaseTable'

export const purchaseData: PurchaseOrder[] = [
  {
    creationDate: '25.10.2023',
    customer: 'ООО "Ромашка"',
    customerInvoice: 'Счет №12 от 13.06.22',
    dealNumber: '22',
    deliveryDeadline: '20.11.2023',
    invoiceLines: [
      {
        article: '1',
        comment: '',
        description: 'Подарочный набор в составе:',
        quantity: 1,
        totalPrice: 111,
        unitPrice: 110,
      },
      {
        article: 'M393A8G40BB4-CWE',
        comment: '',
        description: 'Samsung DDR4 64GB DIMM 3200MHz 2Rx4 Registred ECC',
        quantity: 2,
        totalPrice: 50000,
        unitPrice: 25000,
      },
      {
        article: '3',
        comment: '',
        description: 'Хвост мыши',
        quantity: 1,
        totalPrice: 0,
        unitPrice: 0,
      },
      {
        article: 'x22',
        comment: '',
        description: 'Коврик для мыши',
        quantity: 2,
        totalPrice: 1000,
        unitPrice: 500,
      },
    ],
    logisticsLines: [
      {
        amount: 1000,
        carrier: 'ООО "ТРЕОЛАН"',
        date: '25.10.2023',
        description: 'логистика до нас',
      },
      {
        amount: 4000,
        carrier: 'ООО "DPD"',
        date: '26.10.2023',
        description: 'логистика до клиента',
      },
    ],
    manager: 'Клапанюк Роман Олегович',
    requestNumber: '124',
    supplierLines: [
      {
        article: 'M393A8G40BB4-CWE',
        comment: '',
        daysToDeliver: 0,
        delivered: true,
        description: 'Samsung DDR4 64GB DIMM 3200MHz 2Rx4 Registred ECC',
        paymentDate: '25.10.2023',
        purchaseAmount: 20000,
        quantity: 1,
        shipmentDate: '17.10.2023г.',
        supplier: 'ООО "ТРЕОЛАН"',
        supplierInvoice: 'Счет №: C1263287 от 25.10.2023',
      },
      {
        article: 'M393A8G40BB4-CWE',
        comment: '',
        daysToDeliver: 4,
        delivered: false,
        description: 'Samsung DDR4 64GB DIMM 3200MHz 2Rx4 Registred ECC',
        paymentDate: '25.10.2023',
        purchaseAmount: 30000,
        quantity: 1,
        shipmentDate: '25.11.2023г.',
        supplier: 'ООО "Буян"',
        supplierInvoice: 'Счет №: 18 от 25.10.2023',
      },
      {
        article: '3',
        comment: '',
        daysToDeliver: 0,
        delivered: true,
        description: 'Хвост мыши',
        paymentDate: '20.11.2023',
        purchaseAmount: 0,
        quantity: 1,
        shipmentDate: '17.10.2023г.',
        supplier: 'мышеловка',
        supplierInvoice: '',
      },
      {
        article: 'x22',
        comment: '',
        daysToDeliver: 0,
        delivered: false,
        description: 'Коврик для мыши',
        paymentDate: '21.11.2023',
        purchaseAmount: 500,
        quantity: 1,
        shipmentDate: '17.10.2023г.',
        supplier: 'ООО "Первый"',
        supplierInvoice: 'Счет №: 1 от 25.10.2023',
      },
      {
        article: 'x22',
        comment: '',
        daysToDeliver: 0,
        delivered: true,
        description: 'Коврик для мыши',
        paymentDate: '21.11.2023',
        purchaseAmount: 500,
        quantity: 1,
        shipmentDate: '17.10.2023г.',
        supplier: 'ООО "Второй"',
        supplierInvoice: 'Счет №: 18 от 25.10.2023',
      },
    ],
  },
  {
    creationDate: '25.10.2023',
    customer: 'ООО "Ромашка"',
    customerInvoice: 'Счет №12 от 13.06.22',
    dealNumber: '22',
    deliveryDeadline: '20.11.2023',
    invoiceLines: [
      {
        article: '1',
        comment: '',
        description: 'Подарочный набор в составе:',
        quantity: 1,
        totalPrice: 111,
        unitPrice: 110,
      },
      {
        article: 'M393A8G40BB4-CWE',
        comment: '',
        description: 'Samsung DDR4 64GB DIMM 3200MHz 2Rx4 Registred ECC',
        quantity: 2,
        totalPrice: 50000,
        unitPrice: 25000,
      },
      {
        article: '3',
        comment: '',
        description: 'Хвост мыши',
        quantity: 1,
        totalPrice: 0,
        unitPrice: 0,
      },
      {
        article: 'x22',
        comment: '',
        description: 'Коврик для мыши',
        quantity: 2,
        totalPrice: 1000,
        unitPrice: 500,
      },
    ],
    logisticsLines: [
      {
        amount: 1000,
        carrier: 'ООО "ТРЕОЛАН"',
        date: '25.10.2023',
        description: 'логистика до нас',
      },
      {
        amount: 4000,
        carrier: 'ООО "DPD"',
        date: '26.10.2023',
        description: 'логистика до клиента',
      },
    ],
    manager: 'Клапанюк Роман Олегович',
    requestNumber: '124',
    supplierLines: [
      {
        article: 'M393A8G40BB4-CWE',
        comment: '',
        daysToDeliver: 0,
        delivered: true,
        description: 'Samsung DDR4 64GB DIMM 3200MHz 2Rx4 Registred ECC',
        paymentDate: '25.10.2023',
        purchaseAmount: 20000,
        quantity: 1,
        shipmentDate: '17.10.2023г.',
        supplier: 'ООО "ТРЕОЛАН"',
        supplierInvoice: 'Счет №: C1263287 от 25.10.2023',
      },
      {
        article: 'M393A8G40BB4-CWE',
        comment: '',
        daysToDeliver: 4,
        delivered: false,
        description: 'Samsung DDR4 64GB DIMM 3200MHz 2Rx4 Registred ECC',
        paymentDate: '25.10.2023',
        purchaseAmount: 30000,
        quantity: 1,
        shipmentDate: '25.11.2023г.',
        supplier: 'ООО "Буян"',
        supplierInvoice: 'Счет №: 18 от 25.10.2023',
      },
      {
        article: '3',
        comment: '',
        daysToDeliver: 0,
        delivered: true,
        description: 'Хвост мыши',
        paymentDate: '20.11.2023',
        purchaseAmount: 0,
        quantity: 1,
        shipmentDate: '17.10.2023г.',
        supplier: 'мышеловка',
        supplierInvoice: '',
      },
      {
        article: 'x22',
        comment: '',
        daysToDeliver: 0,
        delivered: false,
        description: 'Коврик для мыши',
        paymentDate: '21.11.2023',
        purchaseAmount: 500,
        quantity: 1,
        shipmentDate: '17.10.2023г.',
        supplier: 'ООО "Первый"',
        supplierInvoice: 'Счет №: 1 от 25.10.2023',
      },
      {
        article: 'x22',
        comment: '',
        daysToDeliver: 0,
        delivered: true,
        description: 'Коврик для мыши',
        paymentDate: '21.11.2023',
        purchaseAmount: 500,
        quantity: 1,
        shipmentDate: '17.10.2023г.',
        supplier: 'ООО "Второй"',
        supplierInvoice: 'Счет №: 18 от 25.10.2023',
      },
    ],
  },
]
