export const ROUTER_PATHS = {
  COMMON_SALES: '/common-sales',
  DEPARTURES: '/departures',
  FINANCES: '/finances',
  HOME: '/',
  MY_SALES: '/my-sales',
  PROCUREMENTS: '/procurements',
  SALARY_REPORTS_COMMON: '/salary-reports-common',
  SALARY_REPORTS_HIMSELF: '/salary-reports-himself',
  SALARY_REPORTS_SELLERS: '/salary-reports-sellers',
  SEE_SELF: '/see-self',
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
  SUMMARY_TABLE: '/summary-table',
  SUPPLIERS: '/suppliers',
} as const
